FROM phpdockerio/php72-fpm:latest
MAINTAINER Developer <info@gluky.co>
WORKDIR /var/www/

# Install modules
RUN apt-get update \
    && apt-get --no-install-recommends install -y \
        apt-utils \
        dnsutils \
        wget \
        mysql-client \
        libcurl4-gnutls-dev libmcrypt-dev libtidy-dev libbz2-dev libxml2-dev libjpeg-dev libfreetype6-dev libjpeg62 libpng-dev libssl-dev libicu-dev libc-client-dev libkrb5-dev \
        jpegoptim \
        libmagickwand-dev \
        php7.2-mysql php-redis php-xdebug php7.2-gd php-imagick php7.2-soap php-ssh2 php-yaml \
    && docker-php-ext-install pdo pdo_mysql \
        bcmath \
        bz2 \
        calendar \
        curl \
        exif \
        ftp \
        gd \
        gettext \
        imap \
        intl \
        json \
        mbstring \
        mcrypt \
        mysqli \
        opcache \
        shmop \
        soap \
        sockets \
        sysvmsg \
        sysvsem \
        sysvshm \
        tidy \
        wddx \
        zip

RUN \
    # default tools
    apt-get install -y zip sudo locales vim nano telnet xvfb yarn gnupg

RUN apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

#       Possible values for ext-name:
#       bcmath bz2 calendar ctype curl dba dom enchant exif fileinfo filter ftp gd gettext gmp hash iconv imap
#       interbase intl json ldap mbstring mcrypt mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql
#       pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline recode reflection session shmop simplexml
#       snmp soap sockets spl standard sysvmsg sysvsem sysvshm tidy tokenizer wddx xml xmlreader xmlrpc xmlwriter xsl zip
